# Generated by Django 4.0.2 on 2022-02-12 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intensity_app', '0004_auto_20220209_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stormdata',
            options={},
        ),
        migrations.RemoveField(
            model_name='stormdata',
            name='category',
        ),
    ]
