# Generated by Django 4.0.2 on 2022-02-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensity_app', '0005_alter_stormdata_options_remove_stormdata_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stormdata',
            options={'ordering': ['storm_name', '-origin_date']},
        ),
        migrations.AddField(
            model_name='stormdata',
            name='category',
            field=models.IntegerField(choices=[(1, 'Category 1'), (2, 'Category 2'), (3, 'Category 3'), (4, 'Category 4'), (5, 'Category 5')], default=1),
        ),
    ]
